language: node_js
node_js:
  - 15
before_install:
  - npm install -g npm@latest
  - npm install -g codecov
script:
  - npm test
  - npm start & wait-on http://localhost:3000
  - npm run cy
after_success:
  - npm run coverage
deploy:
  provide: heroku
  api_key: $HEROKU_AUTH_TOKEN
  app: github-language-analyser
  on: main
